### ISSUE TITLE
More info coming

### ISSUE THREAD

**Issue by davodogster** [placeforyiming/ICCVW21-LiDAR-Panoptic-Segmentation-TradiCV-Survey-of-Point-Cloud-Cluster#1]
Hello! Is the information available?

I want to do tree instance/panoptic segmentation in a high dense point cloud

Cheers,
Sam

**Comment by placeforyiming** [comment]
> Hello! Is the information available?
> 
> I want to do tree instance/panoptic segmentation in a high dense point cloud
> 
> Cheers,
> Sam

Yes, of course. Now I just release the code, I will update the readme soon to give a guide about how to compile and use the code.

**Comment by placeforyiming** [comment]
> Hello! Is the information available?
> 
> I want to do tree instance/panoptic segmentation in a high dense point cloud
> 
> Cheers,
> Sam

Hi, I just updated  the readme file, please take a look.

Thanks for showing interest to our work! Feel free to open an issue if have.

**Comment by davodogster** [comment]
@placeforyiming Thanks!
