### ISSUE TITLE
你好，请问你们使用的trainning和test的dataset分别是velodyne多少线的呢？谢谢 

### ISSUE THREAD

**Issue by ferrari700** [placeforyiming/ICCVW21-LiDAR-Panoptic-Segmentation-TradiCV-Survey-of-Point-Cloud-Cluster#3]

**Comment by placeforyiming** [comment]
> _No description provided._

你好！ 我们是在KITTI的数据集上测试的效果，是64线的激光雷达。只是KITTI的点云数据是经过处理的，如果是原始的数据算法会更快效果更好。另外这个是传统点云聚类算法，因此不需要区分训练和测试，提供semantic的网络这篇论文使用的是Cylinder3D。

**Comment by ferrari700** [comment]
好的，感谢解答！所以我的点云数据是128线的也是可以使用本篇算法吗？谢谢！

**Comment by placeforyiming** [comment]
> 好的，感谢解答！所以我的点云数据是128线的也是可以使用本篇算法吗？谢谢！

可以是肯定可以的。这篇论文主要是review，所以聚类算法是别人的，我们只是提出可以用semantic segmentation加上聚类来进行全景分割。

**Comment by ferrari700** [comment]
> > 好的，感谢解答！所以我的点云数据是128线的也是可以使用本篇算法吗？谢谢！
> 
> 可以是肯定可以的。这篇论文主要是review，所以聚类算法是别人的，我们只是提出可以用semantic segmentation加上聚类来进行全景分割。

所以我只需要将我的激光雷达参数和数据的路径放进semantic_then_instance_post_inferece.py这个档案就行吗？感谢！

**Comment by placeforyiming** [comment]
> > > 好的，感谢解答！所以我的点云数据是128线的也是可以使用本篇算法吗？谢谢！
> > 
> > 
> > 可以是肯定可以的。这篇论文主要是review，所以聚类算法是别人的，我们只是提出可以用semantic segmentation加上聚类来进行全景分割。
> 
> 所以我只需要将我的激光雷达参数和数据的路径放进semantic_then_instance_post_inferece.py这个档案就行吗？感谢！

不行的，我这个是针对KITTI的数据集，需要先有一个semantic segmentation的网络把属于object的点分出来。然后可以比照着KITTI的格式，就可以了。C++实现的函数不依赖别的，所以你弄明白了流程以后，可以只把那一块儿拿出来用

**Comment by ferrari700** [comment]
> > > > 好的，感谢解答！所以我的点云数据是128线的也是可以使用本篇算法吗？谢谢！
> > > 
> > > 
> > > 可以是肯定可以的。这篇论文主要是review，所以聚类算法是别人的，我们只是提出可以用semantic segmentation加上聚类来进行全景分割。
> > 
> > 
> > 所以我只需要将我的激光雷达参数和数据的路径放进semantic_then_instance_post_inferece.py这个档案就行吗？感谢！
> 
> 不行的，我这个是针对KITTI的数据集，需要先有一个semantic segmentation的网络把属于object的点分出来。然后可以比照着KITTI的格式，就可以了。C++实现的函数不依赖别的，所以你弄明白了流程以后，可以只把那一块儿拿出来用

了解了，所以我需要先做128线的point cloud semantic segmentation，我才能使用这个算法对吗？

**Comment by placeforyiming** [comment]
> > > > > 好的，感谢解答！所以我的点云数据是128线的也是可以使用本篇算法吗？谢谢！
> > > > 
> > > > 
> > > > 可以是肯定可以的。这篇论文主要是review，所以聚类算法是别人的，我们只是提出可以用semantic segmentation加上聚类来进行全景分割。
> > > 
> > > 
> > > 所以我只需要将我的激光雷达参数和数据的路径放进semantic_then_instance_post_inferece.py这个档案就行吗？感谢！
> > 
> > 
> > 不行的，我这个是针对KITTI的数据集，需要先有一个semantic segmentation的网络把属于object的点分出来。然后可以比照着KITTI的格式，就可以了。C++实现的函数不依赖别的，所以你弄明白了流程以后，可以只把那一块儿拿出来用
> 
> 了解了，所以我需要先做128线的point cloud semantic segmentation，我才能使用这个算法对吗？

是这样子的

**Comment by placeforyiming** [comment]
Please feel free to open it again if you have further questions
