### ISSUE TITLE
Cannot import name 'Euclidean_Cluster' from 'PC_cluster.Euclidean_cluster.build

### ISSUE THREAD

**Issue by Fatcat3Z** [placeforyiming/ICCVW21-LiDAR-Panoptic-Segmentation-TradiCV-Survey-of-Point-Cloud-Cluster#4]
Hello, when running your code, I encountered the following problem：
`ModuleNotFoundError: No module named 'PC_cluster.depth_cluster.build.Depth_Cluster'`
I make sure that I  follow your  notes and have built the Depth_Cluster.
Hope to get your reply！

**Comment by Fatcat3Z** [comment]
I use another version python with anaconda, then get errors

**Comment by qchenclaire** [comment]
@Fatcat3Z Hi have you got solutions yet?
